spring:
  application:
    name: studyplatform-api

  datasource:
    url: jdbc:postgresql://localhost:5432/studyplatform
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
